window.TransitCities = window.TransitCities || {};

window.TransitCities.gta = {
  id: "gta",
  name: "GTA, Canada",
  summary: "Greater Toronto Area rapid transit sandbox",
  startBudget: 120,
  baseDailyRidershipK: 1580,
  image: {
    src: "assets/gta-dark-map.png",
    width: 10340,
    height: 6975,
    gameplayBaseWidth: 2048,
    gameplayBaseHeight: 1304,
    note: "User-provided dark GTA transit map.",
  },
  mapLabels: [
    { label: "York Region", x: 612, y: 82 },
    { label: "Peel", x: 222, y: 286 },
    { label: "Toronto", x: 560, y: 386 },
    { label: "Durham", x: 885, y: 415 },
    { label: "Lake Ontario", x: 635, y: 623 },
  ],
  sources: [
    {
      label: "Local GTA map image",
      url: "assets/gta-dark-map.png",
    },
    {
      label: "TTC Line 5 opening",
      url: "https://www.ttc.ca/news/2026/February/TTC-to-begin-phased-start-to-service-on-Line-5-Eglinton",
    },
    {
      label: "TTC Line 6 opening",
      url: "https://www.ttc.ca/line6",
    },
    {
      label: "GO Transit maps",
      url: "https://www.gotransit.com/en/system-map",
    },
    {
      label: "Toronto Open Data",
      url: "https://open.toronto.ca/",
    },
  ],
  crews: [
    { id: "cyan", name: "Cyan", color: "#00a8cc" },
    { id: "coral", name: "Coral", color: "#e95f45" },
    { id: "lime", name: "Lime", color: "#4fa64a" },
    { id: "violet", name: "Violet", color: "#7f61d9" },
  ],
  stations: [
    {
      id: "hamilton",
      name: "Hamilton",
      x: 58,
      y: 594,
      role: "Regional rail terminal",
      demand: 3,
      label: true,
      type: "regional",
    },
    {
      id: "oakville",
      name: "Oakville",
      x: 180,
      y: 574,
      role: "Lakeshore West hub",
      demand: 3,
      label: true,
      type: "regional",
    },
    {
      id: "port-credit",
      name: "Port Credit",
      x: 300,
      y: 560,
      role: "Waterfront rail hub",
      demand: 3,
      label: true,
      type: "waterfront",
    },
    {
      id: "exhibition",
      name: "Exhibition",
      x: 458,
      y: 550,
      role: "Event and waterfront station",
      demand: 4,
      label: true,
      type: "waterfront",
    },
    {
      id: "union",
      name: "Union",
      x: 526,
      y: 542,
      role: "Regional hub",
      demand: 5,
      label: true,
      type: "hub",
    },
    {
      id: "danforth-go",
      name: "Danforth GO",
      x: 705,
      y: 518,
      role: "GO and east-end connection",
      demand: 3,
      type: "regional",
    },
    {
      id: "guildwood",
      name: "Guildwood",
      x: 817,
      y: 500,
      role: "Lakeshore East station",
      demand: 2,
      type: "regional",
    },
    {
      id: "oshawa",
      name: "Oshawa",
      x: 956,
      y: 484,
      role: "Durham rail terminal",
      demand: 4,
      label: true,
      type: "regional",
    },
    {
      id: "kitchener",
      name: "Kitchener",
      x: 50,
      y: 352,
      role: "Outer regional terminal",
      demand: 3,
      type: "regional",
    },
    {
      id: "guelph",
      name: "Guelph",
      x: 128,
      y: 338,
      role: "Regional rail station",
      demand: 2,
      type: "regional",
    },
    {
      id: "brampton",
      name: "Brampton",
      x: 228,
      y: 312,
      role: "Regional rail and bus hub",
      demand: 4,
      label: true,
      type: "hub",
    },
    {
      id: "malton",
      name: "Malton",
      x: 296,
      y: 296,
      role: "Airport-area rail station",
      demand: 3,
      type: "regional",
    },
    {
      id: "pearson",
      name: "Pearson",
      x: 246,
      y: 264,
      role: "Airport connection",
      demand: 5,
      label: true,
      type: "airport",
    },
    {
      id: "weston",
      name: "Weston",
      x: 360,
      y: 316,
      role: "Kitchener and UP Express hub",
      demand: 3,
      type: "hub",
    },
    {
      id: "bloor-go",
      name: "Bloor GO/UP",
      x: 426,
      y: 496,
      role: "GO, UP Express, and subway transfer",
      demand: 4,
      type: "hub",
    },
    {
      id: "allandale",
      name: "Allandale",
      x: 382,
      y: 36,
      role: "Barrie line terminal",
      demand: 2,
      type: "regional",
    },
    {
      id: "aurora",
      name: "Aurora",
      x: 452,
      y: 90,
      role: "York Region rail station",
      demand: 2,
      type: "regional",
    },
    {
      id: "rutherford",
      name: "Rutherford",
      x: 434,
      y: 146,
      role: "Vaughan rail station",
      demand: 3,
      type: "regional",
    },
    {
      id: "downsview-park",
      name: "Downsview Park",
      x: 378,
      y: 216,
      role: "GO and Line 1 transfer",
      demand: 3,
      type: "hub",
    },
    {
      id: "old-elm",
      name: "Old Elm",
      x: 874,
      y: 122,
      role: "Stouffville line terminal",
      demand: 2,
      type: "regional",
    },
    {
      id: "unionville",
      name: "Unionville",
      x: 800,
      y: 190,
      role: "Markham regional rail station",
      demand: 3,
      label: true,
      type: "regional",
    },
    {
      id: "milliken",
      name: "Milliken",
      x: 760,
      y: 244,
      role: "North Scarborough station",
      demand: 2,
      type: "regional",
    },
    {
      id: "agincourt",
      name: "Agincourt",
      x: 736,
      y: 302,
      role: "Scarborough rail station",
      demand: 3,
      type: "regional",
    },
    {
      id: "vaughan",
      name: "Vaughan Metropolitan Centre",
      x: 254,
      y: 86,
      role: "Line 1 terminal",
      demand: 4,
      label: true,
      type: "hub",
    },
    {
      id: "highway-407",
      name: "Highway 407",
      x: 282,
      y: 122,
      role: "Regional bus and subway station",
      demand: 3,
      type: "hub",
    },
    {
      id: "york-university",
      name: "York University",
      x: 306,
      y: 158,
      role: "Campus station",
      demand: 4,
      label: true,
      type: "campus",
    },
    {
      id: "finch-west",
      name: "Finch West",
      x: 332,
      y: 190,
      role: "Line 1 and Line 6 transfer",
      demand: 4,
      label: true,
      type: "hub",
    },
    {
      id: "sheppard-west",
      name: "Sheppard West",
      x: 360,
      y: 226,
      role: "Line 1 station",
      demand: 2,
      type: "subway",
    },
    {
      id: "cedarvale",
      name: "Cedarvale",
      x: 430,
      y: 330,
      role: "Line 1 and Line 5 transfer",
      demand: 4,
      label: true,
      type: "hub",
    },
    {
      id: "st-george",
      name: "St George",
      x: 484,
      y: 430,
      role: "Line 1 and Line 2 transfer",
      demand: 5,
      label: true,
      type: "hub",
    },
    {
      id: "bloor-yonge",
      name: "Bloor-Yonge",
      x: 600,
      y: 420,
      role: "Line 1 and Line 2 transfer",
      demand: 5,
      label: true,
      type: "hub",
    },
    {
      id: "eglinton",
      name: "Eglinton",
      x: 604,
      y: 320,
      role: "Line 1 and Line 5 transfer",
      demand: 4,
      label: true,
      type: "hub",
    },
    {
      id: "sheppard-yonge",
      name: "Sheppard-Yonge",
      x: 610,
      y: 230,
      role: "Line 1 and Line 4 transfer",
      demand: 4,
      label: true,
      type: "hub",
    },
    {
      id: "finch",
      name: "Finch",
      x: 612,
      y: 150,
      role: "Line 1 terminal",
      demand: 4,
      label: true,
      type: "subway",
    },
    {
      id: "kipling",
      name: "Kipling",
      x: 246,
      y: 435,
      role: "Line 2 terminal and regional connection",
      demand: 4,
      label: true,
      type: "hub",
    },
    {
      id: "jane",
      name: "Jane",
      x: 344,
      y: 435,
      role: "Line 2 station",
      demand: 2,
      type: "subway",
    },
    {
      id: "dundas-west",
      name: "Dundas West",
      x: 420,
      y: 435,
      role: "Line 2 and streetcar connection",
      demand: 3,
      type: "hub",
    },
    {
      id: "spadina",
      name: "Spadina",
      x: 462,
      y: 435,
      role: "Line 1 and Line 2 transfer area",
      demand: 4,
      type: "hub",
    },
    {
      id: "broadview",
      name: "Broadview",
      x: 650,
      y: 425,
      role: "East-end transfer station",
      demand: 3,
      type: "hub",
    },
    {
      id: "pape",
      name: "Pape",
      x: 690,
      y: 428,
      role: "Line 2 station",
      demand: 3,
      label: true,
      type: "subway",
    },
    {
      id: "main-street",
      name: "Main Street",
      x: 766,
      y: 432,
      role: "Line 2 station",
      demand: 3,
      type: "subway",
    },
    {
      id: "kennedy",
      name: "Kennedy",
      x: 850,
      y: 440,
      role: "Line 2, Line 5, and GO transfer",
      demand: 5,
      label: true,
      type: "hub",
    },
    {
      id: "bayview",
      name: "Bayview",
      x: 665,
      y: 230,
      role: "Line 4 station",
      demand: 2,
      type: "subway",
    },
    {
      id: "leslie",
      name: "Leslie",
      x: 710,
      y: 235,
      role: "Line 4 station",
      demand: 2,
      type: "subway",
    },
    {
      id: "don-mills",
      name: "Don Mills",
      x: 756,
      y: 240,
      role: "Line 4 terminal",
      demand: 4,
      label: true,
      type: "hub",
    },
    {
      id: "mount-dennis",
      name: "Mount Dennis",
      x: 320,
      y: 330,
      role: "Line 5, GO, and UP Express station",
      demand: 4,
      label: true,
      type: "hub",
    },
    {
      id: "keelesdale",
      name: "Keelesdale",
      x: 350,
      y: 330,
      role: "Line 5 station",
      demand: 2,
      type: "lrt",
    },
    {
      id: "caledonia",
      name: "Caledonia",
      x: 380,
      y: 330,
      role: "Line 5 station",
      demand: 3,
      type: "lrt",
    },
    {
      id: "fairbank",
      name: "Fairbank",
      x: 410,
      y: 330,
      role: "Line 5 station",
      demand: 2,
      type: "lrt",
    },
    {
      id: "avenue",
      name: "Avenue",
      x: 510,
      y: 330,
      role: "Line 5 station",
      demand: 2,
      type: "lrt",
    },
    {
      id: "laird",
      name: "Laird",
      x: 666,
      y: 330,
      role: "Line 5 station",
      demand: 3,
      type: "lrt",
    },
    {
      id: "science-centre",
      name: "Science Centre",
      x: 735,
      y: 335,
      role: "Line 5 station",
      demand: 4,
      label: true,
      type: "hub",
    },
    {
      id: "golden-mile",
      name: "Golden Mile",
      x: 810,
      y: 356,
      role: "Line 5 station",
      demand: 3,
      type: "lrt",
    },
    {
      id: "humber-college",
      name: "Humber College",
      x: 170,
      y: 190,
      role: "Line 6 terminal",
      demand: 4,
      label: true,
      type: "campus",
    },
    {
      id: "martin-grove",
      name: "Martin Grove",
      x: 218,
      y: 190,
      role: "Line 6 stop",
      demand: 2,
      type: "lrt",
    },
    {
      id: "albion",
      name: "Albion",
      x: 258,
      y: 190,
      role: "Line 6 stop",
      demand: 2,
      type: "lrt",
    },
    {
      id: "jane-finch",
      name: "Jane and Finch",
      x: 294,
      y: 190,
      role: "Line 6 stop",
      demand: 3,
      type: "lrt",
    },
    {
      id: "square-one",
      name: "Square One",
      x: 230,
      y: 455,
      role: "Mississauga city centre",
      demand: 5,
      label: true,
      type: "growth",
      planned: true,
    },
    {
      id: "scarborough-centre",
      name: "Scarborough Centre",
      x: 840,
      y: 390,
      role: "Scarborough civic and bus hub",
      demand: 5,
      label: true,
      type: "growth",
      planned: true,
    },
    {
      id: "markham-centre",
      name: "Markham Centre",
      x: 800,
      y: 160,
      role: "York Region growth centre",
      demand: 4,
      label: true,
      type: "growth",
      planned: true,
    },
    {
      id: "richmond-hill-centre",
      name: "Richmond Hill Centre",
      x: 642,
      y: 112,
      role: "North Yonge growth centre",
      demand: 4,
      label: true,
      type: "growth",
      planned: true,
    },
    {
      id: "ontario-place",
      name: "Billy Bishop Airport",
      x: 440,
      y: 592,
      role: "Waterfront airport connection",
      demand: 3,
      label: true,
      type: "waterfront",
      planned: true,
    },
    {
      id: "woodbine-centre",
      name: "Woodbine",
      x: 190,
      y: 250,
      role: "Northwest growth area",
      demand: 3,
      type: "growth",
      planned: true,
    },
  ],
  routes: [
    {
      id: "ttc-line-1",
      name: "Line 1",
      color: "#f7d117",
      width: 8,
      mode: "subway",
      labelAt: "st-george",
      stations: [
        "vaughan",
        "highway-407",
        "york-university",
        "finch-west",
        "downsview-park",
        "sheppard-west",
        "cedarvale",
        "st-george",
        "union",
        "bloor-yonge",
        "eglinton",
        "sheppard-yonge",
        "finch",
      ],
    },
    {
      id: "ttc-line-2",
      name: "Line 2",
      color: "#1c9b55",
      width: 8,
      mode: "subway",
      labelAt: "bloor-yonge",
      stations: [
        "kipling",
        "jane",
        "dundas-west",
        "spadina",
        "st-george",
        "bloor-yonge",
        "broadview",
        "pape",
        "main-street",
        "kennedy",
      ],
    },
    {
      id: "ttc-line-4",
      name: "Line 4",
      color: "#8a4fb3",
      width: 7,
      mode: "subway",
      labelAt: "leslie",
      stations: ["sheppard-yonge", "bayview", "leslie", "don-mills"],
    },
    {
      id: "ttc-line-5",
      name: "Line 5",
      color: "#e36a2e",
      width: 7,
      mode: "lrt",
      labelAt: "science-centre",
      stations: [
        "mount-dennis",
        "keelesdale",
        "caledonia",
        "fairbank",
        "cedarvale",
        "avenue",
        "eglinton",
        "laird",
        "science-centre",
        "golden-mile",
        "kennedy",
      ],
    },
    {
      id: "ttc-line-6",
      name: "Line 6",
      color: "#d23f94",
      width: 7,
      mode: "lrt",
      labelAt: "jane-finch",
      stations: [
        "humber-college",
        "martin-grove",
        "albion",
        "jane-finch",
        "finch-west",
      ],
    },
    {
      id: "go-lakeshore",
      name: "Lakeshore GO",
      color: "#0d7f56",
      width: 5,
      mode: "go",
      labelAt: "exhibition",
      stations: [
        "hamilton",
        "oakville",
        "port-credit",
        "exhibition",
        "union",
        "danforth-go",
        "guildwood",
        "oshawa",
      ],
    },
    {
      id: "go-kitchener-up",
      name: "Kitchener/UP",
      color: "#225ea8",
      width: 5,
      mode: "go",
      labelAt: "weston",
      stations: [
        "kitchener",
        "guelph",
        "brampton",
        "malton",
        "pearson",
        "weston",
        "mount-dennis",
        "bloor-go",
        "union",
      ],
    },
    {
      id: "go-barrie",
      name: "Barrie GO",
      color: "#587342",
      width: 5,
      mode: "go",
      labelAt: "downsview-park",
      stations: [
        "allandale",
        "aurora",
        "rutherford",
        "downsview-park",
        "union",
      ],
    },
    {
      id: "go-stouffville",
      name: "Stouffville GO",
      color: "#8d6b27",
      width: 5,
      mode: "go",
      labelAt: "agincourt",
      stations: [
        "old-elm",
        "unionville",
        "milliken",
        "agincourt",
        "kennedy",
        "union",
      ],
    },
  ],
  suggestedLinks: [
    ["pearson", "mount-dennis"],
    ["pearson", "finch-west"],
    ["pearson", "square-one"],
    ["square-one", "kipling"],
    ["square-one", "port-credit"],
    ["scarborough-centre", "kennedy"],
    ["scarborough-centre", "don-mills"],
    ["scarborough-centre", "markham-centre"],
    ["markham-centre", "unionville"],
    ["richmond-hill-centre", "finch"],
    ["richmond-hill-centre", "sheppard-yonge"],
    ["ontario-place", "exhibition"],
    ["ontario-place", "union"],
    ["woodbine-centre", "pearson"],
    ["woodbine-centre", "humber-college"],
  ],
  milestones: [
    {
      id: "airport-relief",
      label: "Add a second rapid transit link to Pearson",
      type: "player-link",
      station: "pearson",
      reward: 18,
    },
    {
      id: "square-one",
      label: "Bring Square One into the connected rapid network",
      type: "served",
      station: "square-one",
      reward: 22,
    },
    {
      id: "scarborough-centre",
      label: "Reconnect Scarborough Centre to rapid transit",
      type: "served",
      station: "scarborough-centre",
      reward: 20,
    },
    {
      id: "north-yonge",
      label: "Connect Richmond Hill Centre to the Line 1 spine",
      type: "served",
      station: "richmond-hill-centre",
      reward: 20,
    },
    {
      id: "waterfront",
      label: "Build a waterfront airport link to Billy Bishop",
      type: "served",
      station: "ontario-place",
      reward: 12,
    },
  ],
  coordinates: {
    hamilton: { x: 1060, y: 6761 },
    oakville: { x: 1626, y: 5750 },
    "port-credit": { x: 1888, y: 5750 },
    exhibition: { x: 3968, y: 5541 },
    union: { x: 5271, y: 5798 },
    "danforth-go": { x: 7291, y: 4589 },
    guildwood: { x: 8401, y: 3573 },
    oshawa: { x: 9330, y: 3348 },
    kitchener: { x: 252, y: 2535 },
    guelph: { x: 571, y: 2471 },
    brampton: { x: 1888, y: 2471 },
    malton: { x: 2615, y: 2477 },
    pearson: { x: 2302, y: 2739 },
    weston: { x: 3317, y: 2931 },
    "bloor-go": { x: 3797, y: 3889 },
    allandale: { x: 4812, y: 225 },
    aurora: { x: 4812, y: 968 },
    rutherford: { x: 4812, y: 1434 },
    "downsview-park": { x: 4761, y: 2017 },
    "old-elm": { x: 8553, y: 765 },
    unionville: { x: 8093, y: 1749 },
    milliken: { x: 8093, y: 1904 },
    agincourt: { x: 8093, y: 2247 },
    vaughan: { x: 4251, y: 1268 },
    "highway-407": { x: 4251, y: 1412 },
    "york-university": { x: 4322, y: 1744 },
    "finch-west": { x: 4645, y: 1904 },
    "sheppard-west": { x: 4796, y: 2439 },
    cedarvale: { x: 4796, y: 3370 },
    "st-george": { x: 5226, y: 4343 },
    "bloor-yonge": { x: 5443, y: 4242 },
    eglinton: { x: 5443, y: 3423 },
    "sheppard-yonge": { x: 5443, y: 2444 },
    finch: { x: 5443, y: 2033 },
    kipling: { x: 2302, y: 4520 },
    jane: { x: 2974, y: 4242 },
    "dundas-west": { x: 3625, y: 4242 },
    spadina: { x: 5019, y: 4242 },
    broadview: { x: 6129, y: 4242 },
    pape: { x: 6523, y: 4242 },
    "main-street": { x: 7482, y: 4242 },
    kennedy: { x: 8088, y: 3354 },
    bayview: { x: 5685, y: 2444 },
    leslie: { x: 6139, y: 2444 },
    "don-mills": { x: 6462, y: 2444 },
    "mount-dennis": { x: 3534, y: 3327 },
    keelesdale: { x: 3862, y: 3370 },
    caledonia: { x: 4069, y: 3370 },
    fairbank: { x: 4322, y: 3370 },
    avenue: { x: 5160, y: 3370 },
    laird: { x: 5958, y: 3423 },
    "science-centre": { x: 6412, y: 3263 },
    "golden-mile": { x: 7533, y: 3423 },
    "humber-college": { x: 2368, y: 2049 },
    "martin-grove": { x: 2595, y: 2049 },
    albion: { x: 2797, y: 2049 },
    "jane-finch": { x: 3938, y: 2049 },
    "square-one": { x: 1111, y: 4482 },
    "scarborough-centre": { x: 8533, y: 2744 },
    "markham-centre": { x: 8401, y: 1273 },
    "richmond-hill-centre": { x: 5725, y: 1401 },
    "ontario-place": { x: 4827, y: 5969 },
    "woodbine-centre": { x: 2959, y: 2578 },
  },
};
